jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Date_of_rate__c.field-meta.xml
<CustomField>
    <fullName>Date_of_rate__c</fullName>
    <label>Date of Rate</label>
    <type>Date</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/ISO_code__c.field-meta.xml
<CustomField>
    <fullName>ISO_code__c</fullName>
    <label>ISO code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/classes/ExchangeRates.cls
public with sharing class ExchangeRates implements Schedulable, Database.AllowsCallouts {

    public static void execute(SchedulableContext sc){
        getExchangeRates();
    }

    /**
     * call CNB API and store values in custom objects
     */

     @future(callout=true)
    public static void getExchangeRates(){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        if(Test.isRunningTest()){
            request.setEndpoint('https://www.cnb.cz');
        }
        else{
            request.setEndpoint('callout:CNB_Exchange_Rates');
        }
        try {
            HttpResponse response = http.send(request);
            List<Exchange_Rate__c> ratesToCreate = parseTXT(response.getBody());

            SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, ratesToCreate);
            insert securityDecision.getRecords();
        } catch (Exception ex) {
            throw new CalloutException('Get Exchange Rates failed: ' + ex);
        }        
    }

    /**
     * parse txt and return list of Exchange_Rate custom objects
     */
    private static List<Exchange_Rate__c> parseTXT(String body){

        List<Exchange_Rate__c> ratesToInsert = new List<Exchange_Rate__c>();
        Date rateDate;
        List<String> lines = body.split('\n');
        for(String line: lines){
            System.debug(line);
            //first line = date
            if(line.contains('#')){
                List<String> firstLine = line.split('#');
                rateDate = Date.parse(firstLine.get(0).trim());                
            }
            else {   
                List<String> elements = line.split('\\|');
                if (elements.get(2).isNumeric()){                       //to bypass second line (header)
                    Exchange_Rate__c exRate = new Exchange_Rate__c();
                    exRate.Date_of_Rate__c = rateDate;
                    exRate.Country__c = elements.get(0);
                    exRate.Currency__c = elements.get(1);
                    exRate.Amount__c = Integer.valueOf(elements.get(2));
                    exRate.ISO_code__c = elements.get(3);
                    exRate.rate__c = Decimal.valueOf(elements.get(4).replace(',', '.'));
                    ratesToInsert.add(exRate);
                }
            }
        }
        return ratesToInsert;
    }
}