jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/ISO_code__c.field-meta.xml
<CustomField>
    <fullName>ISO_code__c</fullName>
    <label>ISO code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/MewsDEV/force-app/main/default/classes/ExchangeRatesTest.cls
@isTest
/**
 * Test class for ExchangeRates Class, using ExchangeRatesTestMock class
 */
public with sharing class ExchangeRatesTest {
    @isTest
    private static void getExchangeRatesTest(){
        Test.setMock(HttpCalloutMock.class, new ExchangeRatesTestMock());
        Test.startTest();
        ExchangeRates.getExchangeRates();
        Test.stopTest();
        List<Exchange_Rate__c> result = [SELECT ID from Exchange_Rate__c];
        System.assertEquals(6, result.size());
        Exchange_Rate__c auDolar = [SELECT ID, Country__c, Amount__c, Rate__c from Exchange_Rate__C where ISO_Code__c = 'AUD' limit 1];
        System.assertEquals(1, auDolar.Amount__c);
        System.assertEquals(14.351, auDolar.Rate__c);
        System.assertEquals('Austrálie', auDolar.Country__c);
    }
}