jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/Currency_Rate__c.object-meta.xml
<CustomObject>
    <description>Custom object to be used with the Exchange Rates Service from and to Czech Koruna</description>
    <label>Currency Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <description>Unit amount of the base currency in the exchange</description>
    <label>Base Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Code__c.field-meta.xml
<CustomField>
    <fullName>Base_Code__c</fullName>
    <description>Currency ISO Code for the base currency in the given exchange rate</description>
    <label>Base Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CZK</fullName>
                <default>true</default>
                <label>CZK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Currency__c</fullName>
    <description>The base currency to which the exchange rates are referring</description>
    <label>Base Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Czech - Koruna</fullName>
                <default>true</default>
                <label>Czech - Koruna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error Message provided by the API, or by the processing Apex</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>/* for a job that runs once a day (every 1440 mins), with an update window of 3 hours (180) */
IF(
   (ROUND(((NOW() - LastModifiedDate)*1440),1) &gt; 1440 + 180), /* Over the update window */
    &apos;Unable to update this rate due to data integrity&apos;, 
    IF(
       NOT(ISBLANK(Error_Message__c)),
       Error_Message__c,
       &apos;Up to date&apos;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <description>Exchange rate for the target currency from the base currency</description>
    <label>Target Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Code__c.field-meta.xml
<CustomField>
    <fullName>Target_Code__c</fullName>
    <description>Currency ISO Code for the target currency in the given exchange rate</description>
    <label>Target Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>ISK</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>RON</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>TRY</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XDR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Currency__c.field-meta.xml
<CustomField>
    <fullName>Target_Currency__c</fullName>
    <description>Name of the currency in English, for example: Australia - Dollar</description>
    <label>Target Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia - Dollar</fullName>
            </value>
            <value>
                <fullName>Brazil - Real</fullName>
            </value>
            <value>
                <fullName>British Pound</fullName>
            </value>
            <value>
                <fullName>Bulgaria - Lev</fullName>
            </value>
            <value>
                <fullName>Canada - Dollar</fullName>
            </value>
            <value>
                <fullName>China - Renminbi</fullName>
            </value>
            <value>
                <fullName>Denmark - Krone</fullName>
            </value>
            <value>
                <fullName>EMU - Euro</fullName>
            </value>
            <value>
                <fullName>Hongkong - Dollar</fullName>
            </value>
            <value>
                <fullName>Hungary - Forint</fullName>
            </value>
            <value>
                <fullName>IMF - SDR</fullName>
            </value>
            <value>
                <fullName>Iceland - Krona</fullName>
            </value>
            <value>
                <fullName>India - Rupee</fullName>
            </value>
            <value>
                <fullName>Indonesia - Rupiah</fullName>
            </value>
            <value>
                <fullName>Israel - New Shekel</fullName>
            </value>
            <value>
                <fullName>Japan - Yen</fullName>
            </value>
            <value>
                <fullName>Malaysia - Ringgit</fullName>
            </value>
            <value>
                <fullName>Mexico - Peso</fullName>
            </value>
            <value>
                <fullName>New Zealand - Dollar</fullName>
            </value>
            <value>
                <fullName>Norway - Krone</fullName>
            </value>
            <value>
                <fullName>Philippines - Peso</fullName>
            </value>
            <value>
                <fullName>Poland - Zloty</fullName>
            </value>
            <value>
                <fullName>Romania - Leu</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
            <value>
                <fullName>Singapore - Dollar</fullName>
            </value>
            <value>
                <fullName>South Africa - Rand</fullName>
            </value>
            <value>
                <fullName>South Korea - Won</fullName>
            </value>
            <value>
                <fullName>Sweden - Krona</fullName>
            </value>
            <value>
                <fullName>Switzerland - Franc</fullName>
            </value>
            <value>
                <fullName>Thailand - Baht</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/classes/ExchangeRatesService.cls
/**
 * @description Service class to hold logic for managing the Exchange Rates logic.
 * The class uses REST http callouts to get the Exchange Rates from and to Czech Koruna via Named Credential endpoint
 * Swagger file = https://api.cnb.cz/cnbapi/swagger-ui.html
 *
 * Execute Anonymous: ExchangeRatesService.getRates(System.now());
 */
public with sharing class ExchangeRatesService {
    @TestVisible
    private static final String CNB_ENDPOINT = 'callout:Czech_National_Bank_Exchange_Rates';
    @TestVisible
    private static final String ASK_HELP = 'Please contact your System Admin for help.';
    @TestVisible
    private static final String CNB_DEFAULT_CURRENCY_NAME = 'Czech - Koruna';
    @TestVisible
    private static final String CNB_DEFAULT_CURRENCY_CODE = 'CZK';

    /**
     * @description Method to allow the package user to test the installation of the package
     * directly from Anonymous Execution without waiting for the scheduled job to run
     */
    public static void testGetRates() {
        ExchangeRatesService.getRates(System.now());
    }

    /**
     * @description Method to get the Exchange Rates from a given Named Credential endpoint
     * and save the result back into SF as sObject records. This main scope will also determins the error message.
     *
     * @param requestedDate DateTime for which the exchange rates should be fetched
     */
    @Future(callout=true)
    public static void getRates(Datetime requestedDate) {
        // create a new HttpRequest and validate the provided param
        HttpRequest req = createHttpRequest(requestedDate);
        if (req == null) {
            handleError('Could not create a valid HttpRequest. ' + ASK_HELP);
            return;
        }

        // make callout and process the response
        HTTPResponse res = new Http().send(req);

        if (res.getStatusCode() != 200) {
            // Bad Request | Not Found | Internal server error
            handleError('Could not update this record due to an external ' + res.getStatusCode() + ' error code. ' + ASK_HELP);
            return;
        }

        String rawResponse = res.getBody();
        String securedResponse = rawResponse.replace('currency', 'currencyName'); // replacing reserved identifiers
        Rates fetchedRates = (Rates) JSON.deserialize(securedResponse, Rates.class);

        // the endpoint will return an empty Rates object if there is no data for the given date
        // over the top safty check in case the records start date will change in the future following a cleanup
        if (fetchedRates.rates.size() == 0 || fetchedRates.rates[0].validFor != (requestedDate).format('yyyy-MM-dd')) {
            handleError('Could not find data for the requested date.');
        }

        Boolean updatedRecords = updateExchangeRates(fetchedRates.rates);

        if (updatedRecords == false) {
            handleError('Could not update this record due to internal processing error. ' + ASK_HELP);
        }
    }

    /**
     * @description Method to update SF with the fetched exchange rates
     * using the object External Id
     *
     * @return Boolean indicator if all possible rates are updated, returns false if there was even 1 failure
     *
     * @param rates List<ExchangeRatesService.CurrencyRate> to be processed
     */
    @TestVisible
    private static Boolean updateExchangeRates(List<CurrencyRate> rates) {
        List<Currency_Rate__c> ratesToUpsert = new List<Currency_Rate__c>();
        for (CurrencyRate rate : rates) {
            String country = fixCapitalization(rate.country);
            String currencyName = fixCapitalization(rate.currencyName);
            ratesToUpsert.add(
                new Currency_Rate__c(
                    Name = CNB_DEFAULT_CURRENCY_CODE + '_' + rate.currencyNameCode,
                    Base_Amount__c = rate.rate,
                    Base_Code__c = CNB_DEFAULT_CURRENCY_CODE,
                    Base_Currency__c = CNB_DEFAULT_CURRENCY_NAME,
                    Error_Message__c = '',
                    Target_Amount__c = rate.amount,
                    Target_Code__c = rate.currencyNameCode,
                    Target_Currency__c = country + ' - ' + currencyName
                )
            );

            ratesToUpsert.add(
                new Currency_Rate__c(
                    Name = rate.currencyNameCode + '_' + CNB_DEFAULT_CURRENCY_CODE,
                    Base_Amount__c = rate.amount,
                    Base_Code__c = rate.currencyNameCode,
                    Base_Currency__c = country + ' - ' + currencyName,
                    Error_Message__c = '',
                    Target_Amount__c = rate.amount / rate.rate,
                    Target_Code__c = CNB_DEFAULT_CURRENCY_CODE,
                    Target_Currency__c = CNB_DEFAULT_CURRENCY_NAME
                )
            );
        }

        // update as many records as possible, and if there was even 1 failure return false
        List<Database.UpsertResult> results = Database.upsert(ratesToUpsert, Currency_Rate__c.Name, false);
        for (Database.upsertResult result : results) {
            if (result.isSuccess() == false) {
                return false;
            }
        }
        return true;
    }

    /**
     * @description Util Method to capitalize given sentences
     *
     * @return String sentece where every word is capitalized
     *
     * @param sentence String where every word should start with an uppercase
     */
    @TestVisible
    private static String fixCapitalization(String sentence) {
        // check if not already uppercase (sign for abbreviation)
        if (sentence.equals(sentence.toUpperCase())) {
            return sentence;
        }

        List<String> words = sentence.toLowerCase().split(' ');
        List<String> capitalized = new List<String>();
        for (String word : words) {
            capitalized.add(word.capitalize());
        }
        return String.join(capitalized, ' ');
    }

    /**
     * @description Method to handle the creation of a new HttpRequest
     *
     * @return HttpRequest with endpoint, and GET method
     *
     * @param requestedDate DateTime for which the exchange rates should be fetched
     */
    @TestVisible
    private static HttpRequest createHttpRequest(Datetime requestedDate) {
        // set the requested date for the callout
        String endPoint = getEndpoint(requestedDate);

        if (String.isBlank(endPoint)) {
            return null;
        }

        HttpRequest req = new HttpRequest();
        req.setEndpoint(endPoint);
        req.setMethod('GET');

        return req;
    }

    /**
     * @description Method to validate the requested date for the API call.
     * While the endpoint will provide a valid response (https://api.cnb.cz/cnbapi/swagger-ui.html) using today's date
     * We want don't want to provide misleading information
     *
     * @return String endpoint containing a valid requested date
     *
     * @param requestedDate DateTime for which the exchange rates should be fetched
     */
    @TestVisible
    private static String getEndpoint(DateTime requestedDate) {
        // validate param to prevent an invalid API call
        if (requestedDate == null || requestedDate > System.now() || requestedDate.year() < 1991) {
            return null;
        }
        // return processed date in the expected format
        return CNB_ENDPOINT + '/daily?date=' + (requestedDate).format('yyyy-MM-dd') + '&lang=EN';
    }

    /**
     * @description Method to handle errors for the request
     * suitable scope for possibility throwing an exception, inserting a new logger record, notifying admin via email, use an event to update UI, etc.
     * in the example below, we are updating the Koruna based records that didn't get updated in the update window with the given error
     *
     * @param errorMsg String - custom text or direct from the endpoint
     */
    @TestVisible
    private static void handleError(String errorMsg) {
        Datetime updateWindow = System.Now().addHours(-3);
        List<Currency_Rate__c> rates = [
            SELECT Id
            FROM Currency_Rate__c
            WHERE Base_Currency__c = 'Czech Koruna' AND LastModifiedDate < :updateWindow
            WITH SYSTEM_MODE
        ];

        for (Currency_Rate__c rate : rates) {
            rate.Error_Message__c = errorMsg;
        }

        // for records that will fail in the DML, we use the Status__c formula as a fallback
        Database.update(rates, false);
    }

    /**
     * @description Decorator class to represent an individual country rate from Czech_National_Bank_Exchange_Rates
     */
    @TestVisible
    private class CurrencyRate {
        public String validFor { get; set; }
        public Integer order { get; set; }
        public String country { get; set; }
        public String currencyName { get; set; } // currency name, for ex: dollar - not unique
        public Integer amount { get; set; }
        public String currencyNameCode { get; set; } // ISO Code
        public Decimal rate { get; set; }
    }

    /**
     * @description Decorator class to process the response from Czech_National_Bank_Exchange_Rates
     */
    @TestVisible
    private class Rates {
        public List<CurrencyRate> rates { get; set; }
    }
}