jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/Currency_Rate__c.object-meta.xml
<CustomObject>
    <description>Custom object to be used with the Exchange Rates Service from and to Czech Koruna</description>
    <label>Currency Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <description>Unit amount of the base currency in the exchange</description>
    <label>Base Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Code__c.field-meta.xml
<CustomField>
    <fullName>Base_Code__c</fullName>
    <description>Currency ISO Code for the base currency in the given exchange rate</description>
    <label>Base Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CZK</fullName>
                <default>true</default>
                <label>CZK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Base_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Currency__c</fullName>
    <description>The base currency to which the exchange rates are referring</description>
    <label>Base Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Czech - Koruna</fullName>
                <default>true</default>
                <label>Czech - Koruna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error Message provided by the API, or by the processing Apex</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <description>Exchange rate for the target currency from the base currency</description>
    <label>Target Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Code__c.field-meta.xml
<CustomField>
    <fullName>Target_Code__c</fullName>
    <description>Currency ISO Code for the target currency in the given exchange rate</description>
    <label>Target Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>ISK</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>RON</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>TRY</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XDR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/objects/Currency_Rate__c/fields/Target_Currency__c.field-meta.xml
<CustomField>
    <fullName>Target_Currency__c</fullName>
    <description>Name of the currency in English, for example: Australia - Dollar</description>
    <label>Target Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia - Dollar</fullName>
            </value>
            <value>
                <fullName>Brazil - Real</fullName>
            </value>
            <value>
                <fullName>British Pound</fullName>
            </value>
            <value>
                <fullName>Bulgaria - Lev</fullName>
            </value>
            <value>
                <fullName>Canada - Dollar</fullName>
            </value>
            <value>
                <fullName>China - Renminbi</fullName>
            </value>
            <value>
                <fullName>Denmark - Krone</fullName>
            </value>
            <value>
                <fullName>EMU - Euro</fullName>
            </value>
            <value>
                <fullName>Hongkong - Dollar</fullName>
            </value>
            <value>
                <fullName>Hungary - Forint</fullName>
            </value>
            <value>
                <fullName>IMF - SDR</fullName>
            </value>
            <value>
                <fullName>Iceland - Krona</fullName>
            </value>
            <value>
                <fullName>India - Rupee</fullName>
            </value>
            <value>
                <fullName>Indonesia - Rupiah</fullName>
            </value>
            <value>
                <fullName>Israel - New Shekel</fullName>
            </value>
            <value>
                <fullName>Japan - Yen</fullName>
            </value>
            <value>
                <fullName>Malaysia - Ringgit</fullName>
            </value>
            <value>
                <fullName>Mexico - Peso</fullName>
            </value>
            <value>
                <fullName>New Zealand - Dollar</fullName>
            </value>
            <value>
                <fullName>Norway - Krone</fullName>
            </value>
            <value>
                <fullName>Philippines - Peso</fullName>
            </value>
            <value>
                <fullName>Poland - Zloty</fullName>
            </value>
            <value>
                <fullName>Romania - Leu</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
            <value>
                <fullName>Singapore - Dollar</fullName>
            </value>
            <value>
                <fullName>South Africa - Rand</fullName>
            </value>
            <value>
                <fullName>South Korea - Won</fullName>
            </value>
            <value>
                <fullName>Sweden - Krona</fullName>
            </value>
            <value>
                <fullName>Switzerland - Franc</fullName>
            </value>
            <value>
                <fullName>Thailand - Baht</fullName>
            </value>
            <value>
                <fullName>dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

jobs/Salesforce/mbmrtt/force-app/main/default/classes/ExchangeRatesServiceTest.cls
@IsTest
public with sharing class ExchangeRatesServiceTest {
    /*****************************
     * Testing Scope without DML *
     *****************************/

    @IsTest
    public static void test_getEndpoint() {
        DateTime requestedDate = null;
        String endpoint = ExchangeRatesService.getEndpoint(requestedDate);
        Assert.isNull(endpoint, 'Expected a null value to return for a null input');

        requestedDate = System.now().addDays(10);
        endpoint = ExchangeRatesService.getEndpoint(requestedDate);
        Assert.isNull(endpoint, 'Expected a null value to return for a future date');

        requestedDate = Datetime.newInstance(1990, 12, 29, 0, 0, 0);
        endpoint = ExchangeRatesService.getEndpoint(requestedDate);
        Assert.isNull(endpoint, 'Expected a null value to return for a date before 1991');

        requestedDate = Datetime.newInstance(1991, 1, 1, 0, 0, 0);
        endpoint = ExchangeRatesService.getEndpoint(requestedDate);
        Assert.isNotNull(endpoint, 'Did not expect a null value for a date within the valid range');

        requestedDate = System.now();
        endpoint = ExchangeRatesService.getEndpoint(requestedDate);
        Assert.isNotNull(endpoint, 'Did not expect a null value for a date within the valid range');

        Assert.isTrue(
            endpoint.contains(ExchangeRatesService.CNB_ENDPOINT + '/daily?date='),
            'Seems like the endpoint changed without updating the test'
        );
    }

    @IsTest
    public static void test_getRates_e2e_noError_InvalidDate() {
        Boolean testPassed = true;

        Test.startTest();
        try {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, false));
            ExchangeRatesService.getRates(Datetime.newInstance(1990, 12, 29, 0, 0, 0));
        } catch (Exception ex) {
            testPassed = false;
        }
        Test.stopTest();

        Assert.isTrue(testPassed, 'Expected the logic to run without throwing an error.');
    }

    @IsTest
    public static void test_getRates_e2e_noError_ValidDateNoData() {
        Boolean testPassed = true;

        Test.startTest();
        try {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, false));
            ExchangeRatesService.getRates(System.now());
        } catch (Exception ex) {
            testPassed = false;
        }
        Test.stopTest();

        Assert.isTrue(testPassed, 'Expected the logic to run without throwing an error.');
    }

    @IsTest
    public static void test_getRates_e2e_noError_200() {
        Boolean testPassed = true;

        Test.startTest();
        try {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, true));
            ExchangeRatesService.getRates(System.now());
        } catch (Exception ex) {
            testPassed = false;
        }
        Test.stopTest();

        Assert.isTrue(testPassed, 'Expected the logic to run without throwing an error.');
    }

    @IsTest
    public static void test_getRates_e2e_noError_404() {
        Boolean testPassed = true;

        Test.startTest();
        try {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(404, true));
            ExchangeRatesService.getRates(System.now());
        } catch (Exception ex) {
            testPassed = false;
        }
        Test.stopTest();

        Assert.isTrue(testPassed, 'Expected the logic to run without throwing an error.');
    }

    /**
     * @description Nested class to mock an HTTP response for ExchangeRatesService
     */
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        private Integer code { get; set; }
        private Boolean returnData { get; set; }

        public MockHttpResponseGenerator(Integer code, Boolean returnData) {
            this.code = code;
            this.returnData = returnData;
        }

        /**
         * @description Method to return a mock HTTP Response for the endpoint Czech_National_Bank_Exchange_Rates
         *
         * @return HttpResponse mocked based on the expected API response
         *
         * @param req HTTPRequest to be mocked
         */
        public HttpResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(code);

            if (code != 200) {
                String error = '{"description": "string","endPoint": "string","errorCode": "INTERNAL_SERVER_ERROR","happenedAt": "2023-07-14T11:00:00","messageId": "string"}';
                res.setBody(error);
                return res;
            }

            if (code == 200 && returnData == false) {
                res.setBody('{"rates":[]}');
                return res;
            }

            ExchangeRatesService.CurrencyRate rate1 = new ExchangeRatesService.CurrencyRate();
            rate1.validFor = '';
            rate1.order = 1;
            rate1.country = 'Australia';
            rate1.currencyName = 'dollar';
            rate1.amount = 1;
            rate1.currencyNameCode = 'AUD';
            rate1.rate = 24.54;

            ExchangeRatesService.CurrencyRate rate2 = new ExchangeRatesService.CurrencyRate();
            rate2.validFor = '';
            rate2.order = 1;
            rate2.country = 'Canada';
            rate2.currencyName = 'dollar';
            rate2.amount = 1;
            rate2.currencyNameCode = 'CAD';
            rate2.rate = 26.145;

            ExchangeRatesService.Rates mockedRates = new ExchangeRatesService.Rates();
            mockedRates.rates = new List<ExchangeRatesService.CurrencyRate>{ rate1, rate2 };

            String mockedSecuredResponse = JSON.serialize(mockedRates);
            String mockedRawResponse = mockedSecuredResponse.replace('currencyName', 'currency');

            res.setBody(mockedRawResponse);
            return res;
        }
    }

    /**************************
     * Testing Scope with DML *
     **************************/

    @IsTest
    static void methodName() {
        List<Currency_Rate__c> rates = getDummyRates();
        insert rates;

        // mock data includes AUD and CAD, while dummy data includes AUD, CAD, HUF, INR and IDR
        List<Currency_Rate__c> commonRates = [
            SELECT Id, Name, Base_Amount__c, Base_Code__c, Base_Currency__c, Error_Message__c, Target_Amount__c, Target_Code__c, Target_Currency__c
            FROM Currency_Rate__c
            WHERE Target_Code__c = 'CAD' OR Target_Code__c = 'AUD'
        ];

        for (Currency_Rate__c rate : commonRates) {
            if (rate.Target_Code__c == 'CAD') {
                Assert.areEqual(16.145, rate.Base_Amount__c);
                Assert.areEqual(1, rate.Target_Amount__c);
            } else {
                Assert.areEqual(14.54, rate.Base_Amount__c);
                Assert.areEqual(1, rate.Target_Amount__c);
            }
        }

        Boolean testPassed = true;

        Test.startTest();
        try {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, true));
            ExchangeRatesService.testGetRates();
        } catch (Exception ex) {
            testPassed = false;
        }
        Test.stopTest();

        // mock data includes AUD and CAD, while dummy data includes AUD, CAD, HUF, INR and IDR
        Assert.isTrue(testPassed, 'Expected the logic to run without throwing an error.');

        commonRates = [
            SELECT Id, Name, Base_Amount__c, Base_Code__c, Base_Currency__c, Error_Message__c, Target_Amount__c, Target_Code__c, Target_Currency__c
            FROM Currency_Rate__c
            WHERE Target_Code__c = 'CAD' OR Target_Code__c = 'AUD'
        ];

        for (Currency_Rate__c rate : commonRates) {
            if (rate.Target_Code__c == 'CAD') {
                Assert.areEqual(26.145, rate.Base_Amount__c);
                Assert.areEqual(1, rate.Target_Amount__c);
            } else {
                Assert.areEqual(24.54, rate.Base_Amount__c);
                Assert.areEqual(1, rate.Target_Amount__c);
            }
        }
    }

    private static List<Currency_Rate__c> getDummyRates() {
        List<Currency_Rate__c> rates = new List<Currency_Rate__c>();

        rates.add(
            new Currency_Rate__c(
                Name = 'CZK_CAD',
                Base_Amount__c = 16.145,
                Base_Code__c = 'CZK',
                Base_Currency__c = 'Czech Koruna',
                Error_Message__c = '',
                Target_Amount__c = 1,
                Target_Code__c = 'CAD',
                Target_Currency__c = 'Canada - Dollar'
            )
        );

        rates.add(
            new Currency_Rate__c(
                Name = 'CZK_AUD',
                Base_Amount__c = 14.54,
                Base_Code__c = 'CZK',
                Base_Currency__c = 'Czech Koruna',
                Error_Message__c = '',
                Target_Amount__c = 1,
                Target_Code__c = 'AUD',
                Target_Currency__c = 'Australia - Dollar'
            )
        );

        rates.add(
            new Currency_Rate__c(
                Name = 'CZK_HUF',
                Base_Amount__c = 6.352,
                Base_Code__c = 'CZK',
                Base_Currency__c = 'Czech Koruna',
                Error_Message__c = '',
                Target_Amount__c = 100,
                Target_Code__c = 'HUF',
                Target_Currency__c = 'Hungary - Rupiah'
            )
        );

        rates.add(
            new Currency_Rate__c(
                Name = 'CZK_INR',
                Base_Amount__c = 25.791,
                Base_Code__c = 'CZK',
                Base_Currency__c = 'Czech Koruna',
                Error_Message__c = '',
                Target_Amount__c = 100,
                Target_Code__c = 'INR',
                Target_Currency__c = 'India - Rupee'
            )
        );

        rates.add(
            new Currency_Rate__c(
                Name = 'CZK_IDR',
                Base_Amount__c = 1.417,
                Base_Code__c = 'CZK',
                Base_Currency__c = 'Czech Koruna',
                Error_Message__c = '',
                Target_Amount__c = 1000,
                Target_Code__c = 'IDR',
                Target_Currency__c = 'Indonesia - Rupiah'
            )
        );

        return rates;
    }
}